apiVersion: v1
kind: Service
metadata:
  name: external-dns-test
  namespace: default
  labels:
    app: external-dns-test
  annotations:
    external-dns.alpha.kubernetes.io/internal-hostname: "nginx.example.com"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: external-dns-test
  type: ClusterIP
